name: Production deployment of taxi driver app
on:
  push:
    branches:
    - feature-driver

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploying changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODDRIVERHOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd on-demand-mobility-bpp-ui/
          git stash
          git checkout feature-driver
          git pull
          git log -1
          yarn
          yarn build
          pm2 kill
          sleep 10
          pm2 serve build 5000 --spa
